"""add water and sewer module tables

Revision ID: 5b03b21aca3b
Revises: h3e5f7a89b10
Create Date: 2026-03-28 19:32:02.348431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b03b21aca3b'
down_revision: Union[str, None] = 'h3e5f7a89b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manhole_type',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sewer_material_type',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('expected_life_years', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sewer_pipe_shape',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('water_material_type',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('expected_life_years', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('water_valve_type',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('exercise_interval_days', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('lift_station',
    sa.Column('lift_station_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('station_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('wet_well_depth_ft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wet_well_diameter_ft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wet_well_material', sa.String(length=30), nullable=True),
    sa.Column('pump_count', sa.SmallInteger(), nullable=True),
    sa.Column('pump_type', sa.String(length=30), nullable=True),
    sa.Column('pump_hp', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('firm_capacity_gpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('design_capacity_gpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('control_type', sa.String(length=30), nullable=True),
    sa.Column('has_scada', sa.Boolean(), nullable=True),
    sa.Column('has_backup_power', sa.Boolean(), nullable=True),
    sa.Column('backup_power_type', sa.String(length=30), nullable=True),
    sa.Column('has_alarm', sa.Boolean(), nullable=True),
    sa.Column('alarm_type', sa.String(length=30), nullable=True),
    sa.Column('electrical_service', sa.String(length=30), nullable=True),
    sa.Column('voltage', sa.SmallInteger(), nullable=True),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('maintained_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('lift_station_id')
    )
    op.create_index(op.f('ix_lift_station_asset_tag'), 'lift_station', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_lift_station_tenant_id'), 'lift_station', ['tenant_id'], unique=False)
    op.create_table('manhole',
    sa.Column('manhole_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('manhole_type_code', sa.String(length=30), nullable=True),
    sa.Column('material', sa.String(length=30), nullable=True),
    sa.Column('diameter_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rim_elevation_ft', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('invert_elevation_ft', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('depth_ft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cover_type', sa.String(length=30), nullable=True),
    sa.Column('cover_diameter_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('frame_type', sa.String(length=30), nullable=True),
    sa.Column('has_steps', sa.Boolean(), nullable=True),
    sa.Column('step_material', sa.String(length=30), nullable=True),
    sa.Column('cone_type', sa.String(length=20), nullable=True),
    sa.Column('chimney_height_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('channel_type', sa.String(length=20), nullable=True),
    sa.Column('bench_type', sa.String(length=20), nullable=True),
    sa.Column('system_type', sa.String(length=20), nullable=False),
    sa.Column('macp_grade', sa.SmallInteger(), nullable=True),
    sa.Column('macp_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('last_macp_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['manhole_type_code'], ['manhole_type.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('manhole_id')
    )
    op.create_index(op.f('ix_manhole_asset_tag'), 'manhole', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_manhole_tenant_id'), 'manhole', ['tenant_id'], unique=False)
    op.create_table('pressure_zone',
    sa.Column('pressure_zone_id', sa.UUID(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('zone_number', sa.String(length=20), nullable=True),
    sa.Column('target_pressure_min_psi', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('target_pressure_max_psi', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('pressure_zone_id'),
    sa.UniqueConstraint('tenant_id', 'zone_name', name='uq_pressure_zone_name')
    )
    op.create_index(op.f('ix_pressure_zone_tenant_id'), 'pressure_zone', ['tenant_id'], unique=False)
    op.create_table('sewer_fitting',
    sa.Column('sewer_fitting_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('fitting_type', sa.String(length=20), nullable=False),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('primary_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('secondary_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['material_code'], ['sewer_material_type.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('sewer_fitting_id')
    )
    op.create_index(op.f('ix_sewer_fitting_asset_tag'), 'sewer_fitting', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_sewer_fitting_tenant_id'), 'sewer_fitting', ['tenant_id'], unique=False)
    op.create_table('water_fitting',
    sa.Column('water_fitting_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('fitting_type', sa.String(length=20), nullable=False),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('primary_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('secondary_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['material_code'], ['water_material_type.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('water_fitting_id')
    )
    op.create_index(op.f('ix_water_fitting_asset_tag'), 'water_fitting', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_water_fitting_tenant_id'), 'water_fitting', ['tenant_id'], unique=False)
    op.create_table('force_main',
    sa.Column('force_main_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('diameter_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('length_feet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pressure_class', sa.String(length=30), nullable=True),
    sa.Column('depth_feet', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lift_station_id', sa.UUID(), nullable=True),
    sa.Column('discharge_manhole_id', sa.UUID(), nullable=True),
    sa.Column('has_cathodic_protection', sa.Boolean(), nullable=True),
    sa.Column('cp_test_date', sa.Date(), nullable=True),
    sa.Column('arv_count', sa.SmallInteger(), nullable=True),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('maintained_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['discharge_manhole_id'], ['manhole.manhole_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lift_station_id'], ['lift_station.lift_station_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_code'], ['sewer_material_type.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('force_main_id')
    )
    op.create_index(op.f('ix_force_main_asset_tag'), 'force_main', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_force_main_tenant_id'), 'force_main', ['tenant_id'], unique=False)
    op.create_table('manhole_pipe',
    sa.Column('manhole_pipe_id', sa.UUID(), nullable=False),
    sa.Column('manhole_id', sa.UUID(), nullable=False),
    sa.Column('pipe_type', sa.String(length=20), nullable=False),
    sa.Column('pipe_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('invert_elevation_ft', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('clock_position', sa.String(length=10), nullable=True),
    sa.Column('pipe_diameter_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['manhole_id'], ['manhole.manhole_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('manhole_pipe_id'),
    sa.UniqueConstraint('manhole_id', 'pipe_type', 'pipe_id', name='uq_manhole_pipe')
    )
    op.create_index(op.f('ix_manhole_pipe_tenant_id'), 'manhole_pipe', ['tenant_id'], unique=False)
    op.create_table('sewer_main',
    sa.Column('sewer_main_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('shape_code', sa.String(length=20), nullable=True),
    sa.Column('diameter_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('height_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('width_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('length_feet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lining_type', sa.String(length=30), nullable=True),
    sa.Column('lining_date', sa.Date(), nullable=True),
    sa.Column('lining_thickness_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('depth_ft_upstream', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('depth_ft_downstream', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('slope_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('upstream_invert_ft', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('downstream_invert_ft', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('upstream_manhole_id', sa.UUID(), nullable=True),
    sa.Column('downstream_manhole_id', sa.UUID(), nullable=True),
    sa.Column('system_type', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('maintained_by', sa.String(length=100), nullable=True),
    sa.Column('pacp_grade', sa.SmallInteger(), nullable=True),
    sa.Column('pacp_structural_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pacp_om_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('last_pacp_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('expected_life_years', sa.SmallInteger(), nullable=True),
    sa.Column('replacement_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['downstream_manhole_id'], ['manhole.manhole_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_code'], ['sewer_material_type.code'], ),
    sa.ForeignKeyConstraint(['shape_code'], ['sewer_pipe_shape.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['upstream_manhole_id'], ['manhole.manhole_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sewer_main_id')
    )
    op.create_index(op.f('ix_sewer_main_asset_tag'), 'sewer_main', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_sewer_main_tenant_id'), 'sewer_main', ['tenant_id'], unique=False)
    op.create_table('water_main',
    sa.Column('water_main_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('diameter_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('length_feet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pressure_class', sa.String(length=30), nullable=True),
    sa.Column('shape', sa.String(length=20), nullable=True),
    sa.Column('lining_type', sa.String(length=30), nullable=True),
    sa.Column('lining_date', sa.Date(), nullable=True),
    sa.Column('depth_feet', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('soil_type', sa.String(length=30), nullable=True),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('maintained_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('expected_life_years', sa.SmallInteger(), nullable=True),
    sa.Column('replacement_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('flow_direction', sa.String(length=20), nullable=True),
    sa.Column('pressure_zone_id', sa.UUID(), nullable=True),
    sa.Column('upstream_node_type', sa.String(length=30), nullable=True),
    sa.Column('upstream_node_id', sa.UUID(), nullable=True),
    sa.Column('downstream_node_type', sa.String(length=30), nullable=True),
    sa.Column('downstream_node_id', sa.UUID(), nullable=True),
    sa.Column('break_count', sa.Integer(), nullable=False),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['material_code'], ['water_material_type.code'], ),
    sa.ForeignKeyConstraint(['pressure_zone_id'], ['pressure_zone.pressure_zone_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('water_main_id')
    )
    op.create_index(op.f('ix_water_main_asset_tag'), 'water_main', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_water_main_tenant_id'), 'water_main', ['tenant_id'], unique=False)
    op.create_table('water_valve',
    sa.Column('water_valve_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('valve_type_code', sa.String(length=30), nullable=True),
    sa.Column('size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=30), nullable=True),
    sa.Column('turns_to_close', sa.SmallInteger(), nullable=True),
    sa.Column('turn_direction', sa.String(length=3), nullable=True),
    sa.Column('normal_position', sa.String(length=10), nullable=False),
    sa.Column('current_position', sa.String(length=10), nullable=True),
    sa.Column('is_operable', sa.String(length=10), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('installation_type', sa.String(length=20), nullable=True),
    sa.Column('depth_feet', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('last_exercised_date', sa.Date(), nullable=True),
    sa.Column('exercise_interval_days', sa.SmallInteger(), nullable=True),
    sa.Column('pressure_zone_id', sa.UUID(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['pressure_zone_id'], ['pressure_zone.pressure_zone_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['valve_type_code'], ['water_valve_type.code'], ),
    sa.PrimaryKeyConstraint('water_valve_id')
    )
    op.create_index(op.f('ix_water_valve_asset_tag'), 'water_valve', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_water_valve_tenant_id'), 'water_valve', ['tenant_id'], unique=False)
    op.create_table('fire_hydrant',
    sa.Column('hydrant_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year_manufactured', sa.SmallInteger(), nullable=True),
    sa.Column('barrel_type', sa.String(length=20), nullable=True),
    sa.Column('nozzle_count', sa.SmallInteger(), nullable=True),
    sa.Column('nozzle_sizes', sa.String(length=50), nullable=True),
    sa.Column('flow_test_date', sa.Date(), nullable=True),
    sa.Column('static_pressure_psi', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('residual_pressure_psi', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pitot_pressure_psi', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('flow_gpm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_class_color', sa.String(length=20), nullable=True),
    sa.Column('last_flush_date', sa.Date(), nullable=True),
    sa.Column('flush_interval_days', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('out_of_service_reason', sa.String(length=200), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('ownership', sa.String(length=20), nullable=False),
    sa.Column('auxiliary_valve_id', sa.UUID(), nullable=True),
    sa.Column('lateral_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('main_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('connected_main_id', sa.UUID(), nullable=True),
    sa.Column('pressure_zone_id', sa.UUID(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['auxiliary_valve_id'], ['water_valve.water_valve_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connected_main_id'], ['water_main.water_main_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['pressure_zone_id'], ['pressure_zone.pressure_zone_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('hydrant_id')
    )
    op.create_index(op.f('ix_fire_hydrant_asset_tag'), 'fire_hydrant', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_fire_hydrant_tenant_id'), 'fire_hydrant', ['tenant_id'], unique=False)
    op.create_table('sewer_lateral',
    sa.Column('sewer_lateral_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=20), nullable=True),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('diameter_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('length_feet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('depth_at_main_ft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('connected_main_id', sa.UUID(), nullable=True),
    sa.Column('tap_location', sa.String(length=30), nullable=True),
    sa.Column('has_cleanout', sa.Boolean(), nullable=True),
    sa.Column('cleanout_location', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['connected_main_id'], ['sewer_main.sewer_main_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['material_code'], ['sewer_material_type.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('sewer_lateral_id')
    )
    op.create_index(op.f('ix_sewer_lateral_account_number'), 'sewer_lateral', ['account_number'], unique=False)
    op.create_index(op.f('ix_sewer_lateral_asset_tag'), 'sewer_lateral', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_sewer_lateral_tenant_id'), 'sewer_lateral', ['tenant_id'], unique=False)
    op.create_table('water_service',
    sa.Column('water_service_id', sa.UUID(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('meter_number', sa.String(length=50), nullable=True),
    sa.Column('meter_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('meter_type', sa.String(length=30), nullable=True),
    sa.Column('service_line_material', sa.String(length=20), nullable=True),
    sa.Column('service_line_size_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tap_main_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('curb_stop_location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['tap_main_id'], ['water_main.water_main_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('water_service_id')
    )
    op.create_index(op.f('ix_water_service_account_number'), 'water_service', ['account_number'], unique=False)
    op.create_index(op.f('ix_water_service_asset_tag'), 'water_service', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_water_service_meter_number'), 'water_service', ['meter_number'], unique=False)
    op.create_index(op.f('ix_water_service_tenant_id'), 'water_service', ['tenant_id'], unique=False)
    op.create_table('water_valve_main',
    sa.Column('water_valve_main_id', sa.UUID(), nullable=False),
    sa.Column('water_valve_id', sa.UUID(), nullable=False),
    sa.Column('water_main_id', sa.UUID(), nullable=False),
    sa.Column('position_on_main', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['water_main_id'], ['water_main.water_main_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['water_valve_id'], ['water_valve.water_valve_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('water_valve_main_id'),
    sa.UniqueConstraint('water_valve_id', 'water_main_id', name='uq_valve_main')
    )
    op.create_index(op.f('ix_water_valve_main_tenant_id'), 'water_valve_main', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_valve_main_tenant_id'), table_name='water_valve_main')
    op.drop_table('water_valve_main')
    op.drop_index(op.f('ix_water_service_tenant_id'), table_name='water_service')
    op.drop_index(op.f('ix_water_service_meter_number'), table_name='water_service')
    op.drop_index(op.f('ix_water_service_asset_tag'), table_name='water_service')
    op.drop_index(op.f('ix_water_service_account_number'), table_name='water_service')
    op.drop_table('water_service')
    op.drop_index(op.f('ix_sewer_lateral_tenant_id'), table_name='sewer_lateral')
    op.drop_index(op.f('ix_sewer_lateral_asset_tag'), table_name='sewer_lateral')
    op.drop_index(op.f('ix_sewer_lateral_account_number'), table_name='sewer_lateral')
    op.drop_table('sewer_lateral')
    op.drop_index(op.f('ix_fire_hydrant_tenant_id'), table_name='fire_hydrant')
    op.drop_index(op.f('ix_fire_hydrant_asset_tag'), table_name='fire_hydrant')
    op.drop_table('fire_hydrant')
    op.drop_index(op.f('ix_water_valve_tenant_id'), table_name='water_valve')
    op.drop_index(op.f('ix_water_valve_asset_tag'), table_name='water_valve')
    op.drop_table('water_valve')
    op.drop_index(op.f('ix_water_main_tenant_id'), table_name='water_main')
    op.drop_index(op.f('ix_water_main_asset_tag'), table_name='water_main')
    op.drop_table('water_main')
    op.drop_index(op.f('ix_sewer_main_tenant_id'), table_name='sewer_main')
    op.drop_index(op.f('ix_sewer_main_asset_tag'), table_name='sewer_main')
    op.drop_table('sewer_main')
    op.drop_index(op.f('ix_manhole_pipe_tenant_id'), table_name='manhole_pipe')
    op.drop_table('manhole_pipe')
    op.drop_index(op.f('ix_force_main_tenant_id'), table_name='force_main')
    op.drop_index(op.f('ix_force_main_asset_tag'), table_name='force_main')
    op.drop_table('force_main')
    op.drop_index(op.f('ix_water_fitting_tenant_id'), table_name='water_fitting')
    op.drop_index(op.f('ix_water_fitting_asset_tag'), table_name='water_fitting')
    op.drop_table('water_fitting')
    op.drop_index(op.f('ix_sewer_fitting_tenant_id'), table_name='sewer_fitting')
    op.drop_index(op.f('ix_sewer_fitting_asset_tag'), table_name='sewer_fitting')
    op.drop_table('sewer_fitting')
    op.drop_index(op.f('ix_pressure_zone_tenant_id'), table_name='pressure_zone')
    op.drop_table('pressure_zone')
    op.drop_index(op.f('ix_manhole_tenant_id'), table_name='manhole')
    op.drop_index(op.f('ix_manhole_asset_tag'), table_name='manhole')
    op.drop_table('manhole')
    op.drop_index(op.f('ix_lift_station_tenant_id'), table_name='lift_station')
    op.drop_index(op.f('ix_lift_station_asset_tag'), table_name='lift_station')
    op.drop_table('lift_station')
    op.drop_table('water_valve_type')
    op.drop_table('water_material_type')
    op.drop_table('sewer_pipe_shape')
    op.drop_table('sewer_material_type')
    op.drop_table('manhole_type')
    # ### end Alembic commands ###
