"""initial schema

Revision ID: 6a817a5cd8ef
Revises:
Create Date: 2026-03-21 22:40:30.905000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a817a5cd8ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_type',
    sa.Column('mutcd_code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('standard_width', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('standard_height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('shape', sa.String(length=30), nullable=True),
    sa.Column('background_color', sa.String(length=30), nullable=True),
    sa.Column('legend_color', sa.String(length=30), nullable=True),
    sa.Column('default_sheeting_type', sa.String(length=30), nullable=True),
    sa.Column('expected_life_years', sa.SmallInteger(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('mutcd_code')
    )
    op.create_index(op.f('ix_sign_type_category'), 'sign_type', ['category'], unique=False)
    op.create_table('tenant',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('tenant_type', sa.String(length=30), nullable=False),
    sa.Column('isolation_model', sa.String(length=20), nullable=False),
    sa.Column('modules_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_table('app_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('modules_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_auth_id', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('external_auth_id')
    )
    op.create_index(op.f('ix_app_user_tenant_id'), 'app_user', ['tenant_id'], unique=False)
    op.create_table('attachment',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('attachment_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_attachment_entity_id'), 'attachment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachment_entity_type'), 'attachment', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachment_tenant_id'), 'attachment', ['tenant_id'], unique=False)
    op.create_table('comment',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comment_entity_id'), 'comment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comment_entity_type'), 'comment', ['entity_type'], unique=False)
    op.create_index(op.f('ix_comment_tenant_id'), 'comment', ['tenant_id'], unique=False)
    op.create_table('sign_support',
    sa.Column('support_id', sa.UUID(), nullable=False),
    sa.Column('support_type', sa.String(length=30), nullable=False),
    sa.Column('support_material', sa.String(length=30), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('height_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('support_id')
    )
    # GeoAlchemy2 auto-creates spatial indexes via DDL events — do not duplicate
    op.create_index(op.f('ix_sign_support_tenant_id'), 'sign_support', ['tenant_id'], unique=False)
    op.create_table('sign',
    sa.Column('sign_id', sa.UUID(), nullable=False),
    sa.Column('support_id', sa.UUID(), nullable=True),
    sa.Column('mutcd_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('legend_text', sa.String(length=100), nullable=True),
    sa.Column('sign_category', sa.String(length=30), nullable=True),
    sa.Column('size_width_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('size_height_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('shape', sa.String(length=30), nullable=True),
    sa.Column('background_color', sa.String(length=30), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('road_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('side_of_road', sa.String(length=5), nullable=True),
    sa.Column('intersection_with', sa.String(length=200), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('sheeting_type', sa.String(length=30), nullable=True),
    sa.Column('sheeting_manufacturer', sa.String(length=100), nullable=True),
    sa.Column('expected_life_years', sa.SmallInteger(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('expected_replacement_date', sa.Date(), nullable=True),
    sa.Column('last_measured_date', sa.Date(), nullable=True),
    sa.Column('measured_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('passes_minimum', sa.Boolean(), nullable=True),
    sa.Column('last_inspected_date', sa.Date(), nullable=True),
    sa.Column('last_replaced_date', sa.Date(), nullable=True),
    sa.Column('replacement_cost_estimate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('facing_direction', sa.SmallInteger(), nullable=True),
    sa.Column('mount_height_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('offset_from_road_inches', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['mutcd_code'], ['sign_type.mutcd_code'], ),
    sa.ForeignKeyConstraint(['support_id'], ['sign_support.support_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('sign_id')
    )
    op.create_index(op.f('ix_sign_tenant_id'), 'sign', ['tenant_id'], unique=False)
    op.create_table('work_order',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('work_order_number', sa.String(length=30), nullable=True),
    sa.Column('asset_type', sa.String(length=30), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('sign_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('work_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=200), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('projected_start_date', sa.Date(), nullable=True),
    sa.Column('projected_finish_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_finish_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('labor_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('material_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('equipment_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('materials_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['sign_id'], ['sign.sign_id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('work_order_id')
    )
    op.create_index(op.f('ix_work_order_asset_id'), 'work_order', ['asset_id'], unique=False)
    op.create_index(op.f('ix_work_order_asset_type'), 'work_order', ['asset_type'], unique=False)
    op.create_index(op.f('ix_work_order_tenant_id'), 'work_order', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_order_work_order_number'), 'work_order', ['work_order_number'], unique=True)
    op.create_table('inspection',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('sign_id', sa.UUID(), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('inspection_type', sa.String(length=50), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('defects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('repairs_made', sa.Text(), nullable=True),
    sa.Column('retroreflectivity_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('passes_minimum_retro', sa.Boolean(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_work_order_id', sa.UUID(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['sign_id'], ['sign.sign_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.work_order_id'], ),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    op.create_index(op.f('ix_inspection_asset_id'), 'inspection', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inspection_asset_type'), 'inspection', ['asset_type'], unique=False)
    op.create_index(op.f('ix_inspection_tenant_id'), 'inspection', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_tenant_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_asset_type'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_asset_id'), table_name='inspection')
    op.drop_table('inspection')
    op.drop_index(op.f('ix_work_order_work_order_number'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_tenant_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_asset_type'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_asset_id'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_sign_tenant_id'), table_name='sign')
    op.drop_table('sign')
    op.drop_index(op.f('ix_sign_support_tenant_id'), table_name='sign_support')
    op.drop_table('sign_support')
    op.drop_index(op.f('ix_comment_tenant_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_entity_type'), table_name='comment')
    op.drop_index(op.f('ix_comment_entity_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_attachment_tenant_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_entity_type'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_entity_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_app_user_tenant_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_sign_type_category'), table_name='sign_type')
    op.drop_table('sign_type')
    # ### end Alembic commands ###
