"""add clerk_org_id to tenant

Revision ID: e41c401e73bb
Revises: 0fde69ac1585
Create Date: 2026-03-21 23:27:55.979879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e41c401e73bb'
down_revision: Union[str, None] = '0fde69ac1585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('clerk_org_id', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'tenant', ['clerk_org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant', type_='unique')
    op.drop_column('tenant', 'clerk_org_id')
    # ### end Alembic commands ###
