"""
Pay Item Categorization System — ported from BidParser (archived/parser/payitems/categories.py)

Maps IDOT pay item codes to divisions and subcategories based on the
Illinois Standard Specifications for Road and Bridge Construction.

Usage:
    division, subcategory = categorize_pay_item("40600105")
    # -> ("BITUMINOUS SURFACES AND HOT-MIX ASPHALT PAVEMENTS",
    #     "HOT-MIX ASPHALT BINDER AND SURFACE COURSE")
"""
from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Division mapping: division name -> (start_code, end_code) inclusive
# ---------------------------------------------------------------------------

DIVISION_RANGES: dict[str, tuple[int, int]] = {
    "GENERAL REQUIREMENTS AND COVENANTS": (101, 109),
    "EARTHWORK": (201, 214),
    "LANDSCAPING": (250, 254),
    "EROSION CONTROL": (280, 285),
    "SUBGRADE": (301, 303),
    "SUBBASE": (310, 312),
    "BASE COURSE": (350, 358),
    "SURFACE COURSE MISCELLANEOUS": (400, 402),
    "BITUMINOUS SURFACES AND HOT-MIX ASPHALT PAVEMENTS": (403, 408),
    "PORTLAND CEMENT CONCRETE PAVEMENTS AND SIDEWALKS": (420, 424),
    "SURFACE COURSE PAVERS AND BRICKS": (430, 430),
    "PAVEMENT REHABILITATION": (440, 452),
    "SHOULDERS": (480, 483),
    "BRIDGES": (501, 522),
    "CULVERTS": (540, 543),
    "SEWERS": (550, 552),
    "UTILITIES": (560, 565),
    "STRUCTURES MISCELLANEOUS": (580, 593),
    "INCIDENTAL CONSTRUCTION DRAINAGE RELATED ITEMS": (601, 611),
    "INCIDENTAL CONSTRUCTION SAFETY RELATED ITEMS": (630, 644),
    "INCIDENTAL CONSTRUCTION OTHER ITEMS": (660, 672),
    "WORK ZONE TRAFFIC CONTROL AND PROTECTION": (701, 708),
    "SIGNING": (720, 738),
    "PAVEMENT MARKING": (780, 783),
    "GENERAL ELECTRICAL REQUIREMENTS": (801, 806),
    "WIREWAY AND CONDUIT SYSTEMS": (810, 815),
    "LIGHTING WIRE AND CABLE": (816, 819),
    "LUMINAIRES": (821, 822),
    "LIGHTING CONTROLLERS": (825, 827),
    "LIGHTING POLES AND TOWERS": (830, 835),
    "LIGHTING FOUNDATIONS AND BREAKAWAY DEVICES": (836, 838),
    "LIGHTING REMOVAL, RELOCATION AND TEMPORARY LIGHTING": (841, 845),
    "TRAFFIC SIGNAL MAINTENANCE": (850, 851),
    "TRAFFIC SIGNAL CONTROLLERS AND EQUIPMENT": (857, 864),
    "TRAFFIC SIGNAL WIRE AND CABLE": (870, 873),
    "TRAFFIC SIGNAL POSTS AND FOUNDATIONS": (875, 879),
    "TRAFFIC SIGNAL HEADS": (880, 883),
    "TRAFFIC SIGNAL DETECTION": (885, 888),
    "TRAFFIC SIGNAL MISCELLANEOUS": (890, 891),
    "TRAFFIC SIGNAL REMOVAL AND RELOCATION": (895, 895),
}

# ---------------------------------------------------------------------------
# Subcategory mapping: code prefix -> subcategory name
# ---------------------------------------------------------------------------

SUBCATEGORY_MAP: dict[int, str] = {
    201: "CLEARING, TREE REMOVAL AND PROTECTION, CARE AND REPAIR OF EXISTING PLANT MATERIAL",
    202: "EARTH AND ROCK EXCAVATION",
    203: "CHANNEL EXCAVATION",
    204: "BORROW AND FURNISHED EXCAVATION",
    205: "EMBANKMENT",
    206: "GRANULAR EMBANKMENT, SPECIAL",
    207: "POROUS GRANULAR EMBANKMENT",
    208: "TRENCH BACKFILL",
    209: "POROUS GRANULAR BACKFILL",
    210: "FABRIC FOR GROUND STABILIZATION",
    211: "TOPSOIL AND COMPOST",
    212: "FINAL SHAPING, TRIMMING, AND FINISHING",
    213: "EXPLORATION TRENCH",
    214: "GRADING AND SHAPING DITCHES",
    250: "SEEDING",
    251: "MULCH",
    252: "SODDING",
    253: "PLANTING WOODY PLANTS",
    254: "PLANTING PERENNIAL PLANTS",
    280: "TEMPORARY EROSION AND SEDIMENT CONTROL",
    281: "RIPRAP",
    282: "FILTER FABRIC",
    283: "AGGREGATE DITCH",
    284: "GABIONS AND SLOPE MATTRESS",
    285: "CONCRETE REVETMENT MATS",
    301: "SUBGRADE PREPARATION",
    302: "SOIL MODIFICATION",
    303: "AGGREGATE SUBGRADE IMPROVEMENT",
    310: "LIME STABILIZED SOIL MIXTURE",
    311: "GRANULAR SUBBASE",
    312: "STABILIZED SUBBASE",
    350: "LIME STABILIZED SOIL MIXTURE",
    351: "AGGREGATE BASE COURSE",
    352: "SOIL-CEMENT BASE COURSE",
    353: "PORTLAND CEMENT CONCRETE BASE COURSE",
    354: "PORTLAND CEMENT CONCRETE BASE COURSE WIDENING",
    355: "HOT-MIX ASPHALT BASE COURSE",
    356: "HOT-MIX ASPHALT BASE COURSE WIDENING",
    357: "RESERVED SECTION",
    358: "REPAIR AND PREPARATION OF BASE COURSE",
    401: "RESERVED SECTION",
    402: "AGGREGATE SURFACE COURSE",
    403: "BITUMINOUS SURFACE TREATMENT (CLASS A-1, A-2, A-3)",
    404: "RESERVED SECTION 405. RESERVED SECTION",
    406: "HOT-MIX ASPHALT BINDER AND SURFACE COURSE",
    407: "HOT-MIX ASPHALT PAVEMENT (FULL-DEPTH)",
    408: "INCIDENTAL HOT-MIX ASPHALT SURFACING",
    420: "PORTLAND CEMENT CONCRETE PAVEMENT",
    421: "CONTINUOUSLY REINFORCED PORTLAND CEMENT CONCRETE PAVEMENT",
    422: "PORTLAND CEMENT CONCRETE RAILROAD CROSSING",
    423: "PORTLAND CEMENT CONCRETE DRIVEWAY PAVEMENT",
    424: "PORTLAND CEMENT CONCRETE SIDEWALK",
    440: "REMOVAL OF EXISTING PAVEMENT AND APPURTENANCES",
    441: "RESERVED",
    442: "PAVEMENT PATCHING",
    443: "REFLECTIVE CRACK CONTROL TREATMENT",
    444: "FIBERGLASS FABRIC REPAIR SYSTEM",
    445: "RESERVED SECTION",
    446: "RESERVED SECTION",
    447: "RESERVED SECTION",
    448: "RESERVED SECTION",
    449: "REMOVAL AND REPLACEMENT OF PREFORMED ELASTOMERIC JOINT SEALS FOR PAVEMENT",
    450: "RELIEF JOINT",
    451: "CRACK SEALING HOT-MIX ASPHALT PAVEMENT",
    452: "CRACK AND JOINT SEALING PORTLAND CEMENT CONCRETE PAVEMENT",
    480: "EARTH SHOULDERS AND MEDIANS",
    481: "AGGREGATE SHOULDERS",
    482: "HOT-MIX ASPHALT SHOULDERS",
    483: "PORTLAND CEMENT CONCRETE SHOULDERS",
    501: "REMOVAL OF EXISTING STRUCTURES",
    502: "EXCAVATION FOR STRUCTURES",
    503: "CONCRETE STRUCTURES",
    504: "PRECAST CONCRETE STRUCTURES",
    505: "STEEL STRUCTURES",
    506: "CLEANING AND PAINTING NEW STEEL STRUCTURES",
    507: "TIMBER STRUCTURES",
    508: "REINFORCEMENT BARS",
    509: "METAL RAILINGS",
    510: "RESERVED SECTION",
    511: "SLOPE WALL",
    512: "PILING",
    513: "TEMPORARY BRIDGES",
    514: "RESERVED SECTION",
    515: "NAME PLATES",
    516: "DRILLED SHAFTS",
    520: "BRIDGE EXPANSION JOINTS",
    521: "BEARINGS",
    522: "RETAINING WALLS",
    540: "BOX CULVERTS",
    541: "RESERVED SECTION",
    542: "PIPE CULVERTS",
    543: "INSERTION LINING OF CULVERTS",
    550: "STORM SEWERS",
    551: "STORM SEWER REMOVAL AND INSTALLATION",
    552: "STORM SEWERS JACKED IN PLACE",
    560: "CAST IRON SOIL PIPE",
    561: "WATER MAIN",
    562: "WATER SERVICE LINE",
    563: "ADJUSTING SANITARY SEWERS AND WATER SERVICE LINES",
    564: "MOVING FIRE HYDRANTS",
    565: "MOVING DOMESTIC METER VAULTS AND WATER SERVICE BOXES",
    580: "MEMBRANE WATERPROOFING FOR RAILWAY STRUCTURES",
    581: "WATERPROOFING MEMBRANE SYSTEM",
    582: "HOT-MIX ASPHALT SURFACING ON BRIDGE DECKS",
    583: "PORTLAND CEMENT MORTAR FAIRING COURSE",
    584: "GROUTING OF ANCHOR RODS AND BARS",
    585: "RESERVED SECTION",
    586: "SAND BACKFILL FOR VAULTED ABUTMENTS",
    587: "CONCRETE SEALER",
    588: "BRIDGE RELIEF JOINT SEALER",
    589: "RESERVED",
    590: "EPOXY CRACK INJECTION",
    591: "GEOCOMPOSITE WALL DRAIN",
    592: "BRIDGE WASHING",
    593: "CONTROLLED LOW-STRENGTH MATERIAL, BACKFILL",
    601: "PIPE DRAINS, PIPE UNDERDRAINS, AND FRENCH DRAINS",
    602: "CATCH BASIN, MANHOLE, INLET, DRAINAGE STRUCTURE, AND VALVE VAULT CONSTRUCTION, ADJUSTMENT, AND RECONSTRUCTION",
    603: "ADJUSTING FRAMES AND GRATES OF DRAINAGE AND UTILITY STRUCTURES",
    604: "FRAMES, GRATES, AND MEDIAN INLETS",
    605: "REMOVING OR FILLING EXISTING MANHOLES, CATCH BASINS, AND INLETS",
    606: "CONCRETE GUTTER, CURB, MEDIAN, AND PAVED DITCH",
    607: "SLUICE GATE",
    608: "FLAP GATES",
    609: "RESERVED SECTION",
    610: "SHOULDER INLETS WITH CURB",
    611: "TREATMENT OF EXISTING FIELD TILE SYSTEMS",
    630: "STEEL PLATE BEAM GUARDRAIL",
    631: "TRAFFIC BARRIER TERMINALS",
    632: "GUARDRAIL AND CABLE ROAD GUARD REMOVAL",
    633: "REMOVING AND REERECTING GUARDRAIL AND TERMINALS",
    634: "GUARD POSTS",
    635: "DELINEATORS",
    636: "CABLE ROAD GUARD",
    637: "CONCRETE BARRIER",
    638: "GLARE SCREEN",
    639: "PRECAST PRESTRESSED CONCRETE SIGHT SCREEN",
    640: "CHAIN LINK FENCE SIGHT SCREEN",
    641: "WOOD FENCE SIGHT SCREEN",
    642: "SHOULDER RUMBLE STRIPS",
    643: "IMPACT ATTENUATORS",
    644: "HIGH TENSION CABLE MEDIAN BARRIER",
    660: "RESERVED SECTION",
    661: "HOT-MIX ASPHALT SHOULDER CURB",
    662: "CONCRETE SHOULDER CURB",
    663: "CALCIUM CHLORIDE APPLIED",
    664: "CHAIN LINK FENCE",
    665: "WOVEN WIRE FENCE",
    666: "RIGHT-OF-WAY MARKERS",
    667: "DRAINAGE MARKERS AND PERMANENT SURVEY MARKERS",
    668: "PRESERVATION OF STONES AND OTHER MARKERS",
    669: "REMOVAL AND DISPOSAL OF REGULATED SUBSTANCES",
    670: "ENGINEER'S FIELD OFFICE AND LABORATORY",
    671: "MOBILIZATION",
    672: "SEALING ABANDONED WATER WELLS",
    701: "WORK ZONE TRAFFIC CONTROL AND PROTECTION",
    702: "NIGHTTIME WORK ZONE LIGHTING",
    703: "WORK ZONE PAVEMENT MARKING",
    704: "TEMPORARY CONCRETE BARRIER",
    705: "TEMPORARY STEEL PLATE BEAM GUARDRAIL",
    706: "IMPACT ATTENUATORS, TEMPORARY",
    707: "MOVABLE TRAFFIC BARRIER",
    708: "TEMPORARY WATER FILLED BARRIER",
    720: "SIGN PANELS AND APPURTENANCES",
    721: "SIGN PANEL OVERLAY",
    722: "DEMOUNTABLE SIGN LEGEND CHARACTERS AND ARROWS",
    723: "INSTALL EXISTING SIGN PANEL",
    724: "REMOVE AND RELOCATE SIGN PANEL AND SIGN PANEL ASSEMBLY",
    725: "OBJECT AND TERMINAL MARKERS",
    726: "MILE POST MARKER ASSEMBLY",
    727: "SIGN SUPPORT - BREAKAWAY",
    728: "TELESCOPING STEEL SIGN SUPPORT",
    729: "METAL POST",
    730: "WOOD SIGN SUPPORT",
    731: "BASE FOR TELESCOPING STEEL SIGN SUPPORT",
    732: "RESERVED SECTION",
    733: "OVERHEAD SIGN STRUCTURES",
    734: "CONCRETE FOUNDATIONS FOR SIGN STRUCTURES",
    735: "REMOVE AND RELOCATE OVERHEAD SIGN STRUCTURE OR GROUND MOUNTED SIGN SUPPORT",
    736: "REMOVE OVERHEAD SIGN STRUCTURE",
    737: "REMOVE GROUND MOUNTED SIGN SUPPORT AND/OR CONCRETE FOUNDATIONS",
    738: "REMOVE, REPLACE, AND RE-ERECT OVERHEAD SIGN STRUCTURE COMPONENTS",
    780: "PAVEMENT STRIPING",
    781: "RAISED REFLECTIVE PAVEMENT MARKERS",
    782: "REFLECTORS",
    783: "PAVEMENT MARKING AND MARKER REMOVAL",
    801: "ELECTRICAL REQUIREMENTS",
    802: "RESERVED SECTION",
    803: "LOCATING UNDERGROUND CABLE",
    804: "ELECTRICAL SERVICE INSTALLATION - LIGHTING",
    805: "ELECTRICAL SERVICE INSTALLATION - TRAFFIC SIGNALS",
    806: "GROUNDING",
    810: "UNDERGROUND RACEWAYS",
    811: "EXPOSED RACEWAYS",
    812: "RACEWAYS EMBEDDED IN STRUCTURE",
    813: "JUNCTION BOXES",
    814: "HANDHOLE",
    815: "GULFBOX JUNCTION",
    816: "UNIT DUCT",
    817: "CABLE IN RACEWAY",
    818: "AERIAL CABLE FOR LIGHTING",
    819: "RESERVED LUMINAIRES SECTION",
    821: "ROADWAY LUMINAIRES",
    822: "NAVIGATION OBSTRUCTION WARNING LUMINAIRES",
    825: "LIGHTING CONTROLLER",
    826: "NAVIGATION OBSTRUCTION LIGHTING CONTROLLER",
    827: "TRANSFORMER, GENERAL PURPOSE",
    830: "LIGHT POLES",
    831: "RESERVED SECTION",
    832: "RESERVED SECTION",
    833: "RESERVED SECTION",
    834: "RESERVED SECTION",
    835: "LIGHT TOWER",
    836: "POLE FOUNDATION",
    837: "LIGHT TOWER FOUNDATION",
    838: "BREAKAWAY DEVICES",
    841: "TEMPORARY LIGHTING REMOVAL",
    842: "REMOVAL OF LIGHTING UNITS",
    843: "REMOVAL OF NAVIGATION OBSTRUCTION WARNING LIGHTING",
    844: "RELOCATE LIGHTING UNITS",
    845: "REMOVAL OF LIGHTING CONTROLLER",
    850: "MAINTENANCE OF EXISTING TRAFFIC SIGNAL INSTALLATION",
    851: "PAINT EXISTING TRAFFIC SIGNAL EQUIPMENT",
    857: "TRAFFIC ACTUATED CONTROLLER",
    858: "FLASHER CONTROLLER",
    859: "TRANSCEIVER",
    860: "MASTER CONTROLLER",
    861: "DIGITAL TIME SWITCH",
    862: "UNINTERRUPTABLE POWER SUPPLY (UPS)",
    863: "CONTROLLER CABINET AND PERIPHERAL EQUIPMENT",
    864: "TRANSCEIVER-FIBER OPTIC",
    870: "MULTI-CONDUCTOR POWER CABLE",
    871: "FIBER OPTIC CABLE",
    872: "SPAN WIRE AND TETHER WIRE",
    873: "ELECTRIC CABLE",
    875: "TRAFFIC SIGNAL POST",
    876: "PEDESTRIAN PUSH-BUTTON POST",
    877: "MAST ARM ASSEMBLY AND POLE",
    878: "TRAFFIC SIGNAL CONCRETE FOUNDATION",
    879: "DRILL EXISTING FOUNDATION OR HANDHOLE",
    880: "LIGHT EMITTING DIODE (LED) SIGNAL HEAD AND OPTICALLY PROGRAMMED LED SIGNAL HEAD",
    881: "LIGHT EMITTING DIODE (LED) PEDESTRIAN SIGNAL HEAD",
    882: "TRAFFIC SIGNAL BACKPLATE",
    883: "DIRECTIONAL LOUVER",
    885: "INDUCTIVE LOOP DETECTOR",
    886: "DETECTOR LOOP",
    887: "EMERGENCY VEHICLE PRIORITY SYSTEM",
    888: "PEDESTRIAN PUSH-BUTTON",
    890: "TEMPORARY TRAFFIC SIGNAL",
    891: "ILLUMINATED SIGN",
    895: "REMOVAL, RELOCATION, AND REBUILDING OF EXISTING SIGNAL AND APPURTENANCES",
}

# ---------------------------------------------------------------------------
# Landscaping letter prefix -> plant type
# ---------------------------------------------------------------------------

LANDSCAPING_PREFIX: dict[str, str] = {
    "A": "TREE",
    "B": "TREE",
    "C": "SHRUB",
    "D": "EVERGREEN",
    "E": "WILDFLOWER",
    "F": "SEEDLING",
    "G": "SEEDLING",
    "H": "SEEDLING",
}

# ---------------------------------------------------------------------------
# Pre-build lookup for divisions (code -> division name)
# ---------------------------------------------------------------------------

_DIVISION_LOOKUP: list[tuple[int, int, str]] = sorted(
    [(start, end, name) for name, (start, end) in DIVISION_RANGES.items()],
    key=lambda x: x[0],
)

RE_NUMERIC_PREFIX = re.compile(r"^(\d{3,})")


def _extract_code_prefix(pay_item_code: str) -> int | None:
    """Extract the 3-digit numeric prefix from a pay item code."""
    match = RE_NUMERIC_PREFIX.match(pay_item_code)
    if not match:
        return None
    # Take first 3 digits
    digits = match.group(1)[:3]
    try:
        return int(digits)
    except ValueError:
        return None


def categorize_pay_item(pay_item_code: str) -> tuple[str, str]:
    """
    Categorize a pay item code into (division, subcategory).

    Args:
        pay_item_code: IDOT pay item code (e.g., "40600105", "250A0010")

    Returns:
        Tuple of (division_name, subcategory_name).
        Returns ("", "") if the code cannot be categorized.
    """
    prefix = _extract_code_prefix(pay_item_code)
    if prefix is None:
        return ("", "")

    # Find division by range
    division = ""
    for start, end, name in _DIVISION_LOOKUP:
        if start <= prefix <= end:
            division = name
            break

    # Find subcategory by exact prefix match
    subcategory = SUBCATEGORY_MAP.get(prefix, "")

    return (division, subcategory)


def get_landscaping_type(pay_item_code: str) -> str | None:
    """
    For landscaping items (codes 250-254), determine plant type from letter prefix.

    Some landscaping codes have a letter prefix (A-H) before the numeric code
    that indicates the plant type.

    Returns:
        Plant type string (e.g., "TREE", "SHRUB") or None if not a landscaping item.
    """
    if not pay_item_code:
        return None

    first_char = pay_item_code[0].upper()
    if first_char in LANDSCAPING_PREFIX:
        # Verify the numeric part falls in the landscaping range
        remaining = pay_item_code[1:]
        prefix = _extract_code_prefix(remaining)
        if prefix and 250 <= prefix <= 254:
            return LANDSCAPING_PREFIX[first_char]

    return None
